pipelines:
  default:
    - step:
        services:
          - docker
        caches:
          - docker
        script:
          - IMAGE_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - echo Logging in to Amazon ECR...
          - docker build -t $IMAGE_NAME:$IMAGE_TAG .
          - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

          # use the pipe to push to AWS ECR
          - pipe: atlassian/aws-ecr-push-image:1.5.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: $IMAGE_NAME
              TAGS: "$IMAGE_TAG latest"

    - step:
        name: "Deploy to PROD"
        deployment: production
        image: amazon/aws-cli:latest
        script:
          - export IMAGE_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
          - yum install -y gettext
          - envsubst < eks-deployment.yml > deployment.yml
          - cat deployment.yml
          - pipe: atlassian/aws-eks-kubectl-run:1.1.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: $IMAGE_NAME
              CLUSTER_NAME: $CLUSTER_NAME
              ACCOUNT_ID: $ACCOUNT_ID
              KUBECTL_COMMAND: "apply"
              RESOURCE_PATH: "deployment.yml"
              DEBUG: "true"