server:
  servlet:
    context-path: /profile

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-west-1
    s3:
      bucket: profile

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error