server:
  servlet:
    context-path: /member

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  datasource:
    jdbc-url: jdbc:mysql://rds-rpm-member.c6o9jygtebcw.ap-northeast-2.rds.amazonaws.com:4306/rpm?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: midasit1!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: dv-rpm-redis-open.q42tke.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    database: 1

  data:
    redis:
      repositories:
        enabled: false

  security:
    oauth2:
      jwt:
        alias: server_private
        code: mid@sit
        expired: 1
        public: /publicKey.txt
        private: /server.jks

springdoc:
  api-docs:
    groups:
      enabled: true

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: rpm-member

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---
spring:
  config:
    activate:
      on-profile: local

  redis:
    host: master.kr-dv-elc-infra1-v1.bhicw6.apn2.cache.amazonaws.com
    port: 4379
    database: 1
    ssl: true